---
name: SkinChangerTests
version: 1.0.0
api: [3.0.0-ALPHA9]
author: BlockHorizons
main: BlockHorizons\Tests\SkinChanger

commands:
  spawntest:
    usage: /spawntest
    description: Spawns a test human.
...